version: 2.1

parameters:
  create-new-branch:
    type: boolean
    default: false
  message-id:
    type: string
    default: ""
  agent-type:
    type: string
    default: ""
  run-pipeline-as-a-tool:
    type: boolean
    default: false
  run-id:
    type: string
    default: ""

workflows:
  cci-agent-setup:
    jobs:
      - cci-agent-setup

jobs:
  cci-agent-setup:
    docker:
      - image: cimg/node:22.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
