version: 2.1

workflows:
  cci-agent-setup:
    jobs:
      - cci-agent-setup

jobs:
  cci-agent-setup:
    docker:
      - image: cimg/node:22.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
